# Generated by Django 4.0 on 2022-01-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name_plural': 'relationship'},
        ),
    ]
