# Generated by Django 4.0 on 2022-01-16 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='motherComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.comment'),
        ),
    ]
