# Generated by Django 4.0 on 2022-01-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(blank=True, to='userProfile.Comment'),
        ),
    ]
