# Generated by Django 4.0 on 2022-01-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_alter_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
