# Generated by Django 4.0 on 2022-01-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_remove_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, to='userProfile.Comment'),
        ),
    ]
