# Generated by Django 4.0 on 2022-01-16 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='motherComment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter your comment: ', max_length=600)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('motherComment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.reply')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.profile')),
            ],
        ),
    ]
