# Generated by Django 4.0 on 2022-01-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_alter_reply_mothercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to='userProfile.Like'),
        ),
    ]
